- id: controller-hiera-override
  type: puppet
  groups: [primary-controller, controller]
  required_for: [openstack-network-start]
  requires: [deploy_start, globals]
  parameters:
    puppet_manifest: puppet/manifests/controller-hiera-override.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 120

# Skip L2, L3, DHCP and Metadata Neutron agents
- id: primary-openstack-network-agents-l3
  type: skipped
- id: openstack-network-agents-l3
  type: skipped
- id: primary-openstack-network-agents-dhcp
  type: skipped
- id: openstack-network-agents-dhcp
  type: skipped
- id: primary-openstack-network-agents-metadata
  type: skipped
- id: openstack-network-agents-metadata
  type: skipped
# Skip default fuel networks and routers
- id: openstack-network-networks
  type: skipped
- id: openstack-network-routers
  type: skipped
- id: primary-openstack-network-plugins-l2
  type: skipped
- id: openstack-network-plugins-l2
  type: skipped
