attributes:
  # Show Nuage plugin option only in supported network config
  metadata:
    restrictions:
      - condition: "not (cluster:net_provider == 'neutron' and networking_parameters:segmentation_type == 'vlan')"
        message: "Please use Neutron with VLAN segmentation, the only network type supported with Nuage plugin."
  nuage_net_partition_name:
    value: ''
    label: 'Nuage Net Partition name'
    description: 'Nuage Net Partition name for VSD'
    weight: 20
    type: "text"
  nuage_vsd_ip:
    value: ''
    label: 'VSD IP address'
    description: 'VSD Management IP address'
    weight: 30
    type: "text"
    regex:
      source: '(^(?:(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))((:8443)|(:443))$'
      error: "Valid format for VSD IP is VSD-IP:8443 for standalone VSD and VSD-IP:443 for clustered VSD"
  nuage_vsd_username:
    value: ''
    label: 'VSD username'
    description: 'VSD user'
    weight: 40
    type: "text"
  nuage_vsd_password:
    value: ''
    label: 'VSD password'
    description: 'VSD password'
    weight: 50
    type: "text"
  nuage_vsd_organization:
    value: ''
    label: 'VSD organization name'
    description: 'VSD organization'
    weight: 60
    type: "text"
  nuage_base_uri_version:
    value: ''
    label: 'Nuage base uri version'
    description: 'Nuage base uri version number'
    weight: 70
    type: "text"
    regex:
      source: '^(v[0-9]{1})_(([0-9]{1}))$'
      error: "Invalid base URI version. Example of valid base uri version : v3_2 for VSP release 3.2"
  nuage_active_vsc_ip:
    value: ''
    label: 'Active VSC IP address'
    description: 'Active VSC IP address'
    weight: 80
    type: "text"
    regex:
      source: '^(?:(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])'
      error: "Invalid Active VSC IP address"
  nuage_backup_vsc_ip:
    value: ''
    label: 'Backup VSC IP address'
    description: 'Backup VSC IP address'
    weight: 90
    type: "text"
    regex:
      source: '(^(?:(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]))|\s+'
      error: "Invalid Standby VSC IP address"
  metadata_port:
    value: '9697'
    label: 'Nuage Metadata agent port number'
    description: 'Nuage Metadata agent port number'
    weight: 100
    type: "text"
  nova_metadata_port:
    value: '8775'
    label: 'Nova metadata port number'
    description: 'Nova metadata port number'
    weight: 110
    type: "text"
  nova_region_name:
    value: 'RegionOne'
    label: 'Nova Region Name'
    description: 'Nova Region name'
    weight: 120
    type: "text"
  nuage_cms_id:
    value: ''
    label: 'Nuage CMS ID'
    description: 'Nuage CMS ID'
    weight: 130
    type: "text"
  pat_to_underlay:
    value: false
    label: "PAT to Underlay"
    description: "If selected, PAT to underlay feature will be enabled"
    weight: 140
    type: "checkbox"
  pat_to_underlay_uplink_intf:
    value: 'br-mgmt'
    label: 'Uplink Interface for PAT to Underlay feature'
    description: 'Provide an uplink interface only if PAT to Underlay feature enabled'
    weight: 150
    type: "text"
  nova_api_endpoint_type:
    type: "radio"
    weight: 160
    value: "publicURL"
    label: "Nova API endpoint type"
    description: "Select Nova API endpoint type"
    values:
      - data: "publicURL"
        label: "publicURL"
      - data: "internalURL"
        label: "internalURL"
      - data: "adminURL"
        label: "adminURL"
